# Specific Projects {#projects}

**Alissa**  
My two main projects are 1) Modeling ITH in cancer cell lines with a focus on dynamics, differential drug sensitivity, and cancer cell-cancer cell interactions in HNSCC (with Rotem). 2) Spatial transcriptomics of GBM (in collaboration with the Suva Lab).

**Rony**  
My thesis focuses on GBM intra-tumor heterogeneity, for which I have 3 projects in collaboration with Mario Suva’s lab at MGH: 1) modeling the GBM states in cancer cell lines and a mouse model of GBM, 2) exploring the GBM microenvironment cell-cell interactions in regards to the cellular states, and 3) targeting the GBM states as a therapeutic approach for GBM.

**Mike**  
My work concerns deconvolution of bulk RNA-seq data to identify signatures of tumour subpopulations or cell states.  My current project focuses on distinguishing EMT (or partial EMT) from stromal cells in bulk transcriptomes.

**Michael**  
My work broadly focuses on ITH in head and neck cancer. In collaboration with Sid Puram’s lab I analyse scRNASeq data from patients with oropharyngeal, laryngeal and oral cavity cancer in order to find tumour genetic subclones and functional metaprograms in the cancer cells and microenvironment.

**Noam H**  
My work is to do a regulatory follow up to lab discoveries on chromatin organization level using single cell ATAC-seq on two main ITH projects: 1) head and neck cancer 2) GBM.

**Julie**  
My work focuses on understanding expression heterogeneity in gliomas. I analyse primarily scRNA-seq data from the Suva lab to 1) define the subpopulations of cancer cells that exist in different glioma types, 2) understand the emergence of these subpopulations as a function of cell lineage, genetics and the TME and 3) revisit the distinctions between glioma types. 

**Noam G**  
My project focuses on deconvolution of bulk RNA-seq data to identify and distinguish IFN response and MHC class ii genes in cancer cells from immune cells. 

