# Joining and Leaving protocol {#joiningLeaving}

## Joining
When joining the group:

1. Ask Michal Ovadia to pool your userID to this department and connect you to any services you may need to use (at least WEXAC and email will be necessary, and RSA very useful), note, if you have userID in other department, pooling you will erase your old server folder. 
2. Ask Michal to add you to the lab dropbox.
3. Order a computer – available options are found at the [DIS site](http://www.weizmann.ac.il/DIS/computing-hardware/pc/windows-laptops)
Check with Itay before ordering.
4. Natali Yikne is the one that supplies network cable, opens the network connection point near to your desk and makes your registration to the internet - for that, you will have to supply your ETHERNET code (found on the Ethernet outlet) and the computer’s MAC address.
5. Ask Itay to get the lab google calendar so you can update and know future plans. 
6. If you’re a foreigner, go to the FGS for help to set up banking and insurance.
7. Also as a foreigner you can [arrange housing through the visiting scientist centre](http://www.weizmann.ac.il/vs/).
8. Provide your bank account to Michal so you can get paid.
9. After registering you will get emails about doing a medical checkup, lab safety introduction and having your photo taken so you can get a Weizmann badge.

## Leaving
When leaving the group:

1. Make sure to return all your computer accessories (docking station, charger, mouse, keyboard etc)
2. Make sure to back up your code, results and data, as your folder will be erased.
3. Talk to Michal to remove you from services.
4. Return your badge to Michal when you leave.
5. Notify Natali whether you possess Weizmann laptop and accessories and who will get that after you.

