# Lab Responsibilities {#labResponsibilities}

Experimental-related:
(Alissa, Rony, Rotem, Debdatta)
1. Warehouse orders – Alissa & Rony
2. Equipment/reagents maintenance:
	+Autoclave - preparation of materials (eppendorfs, Pasteur pipettes, H20) and transporting to/from autoclave on 3rd floor - Rotem
	+Waste disposal - bringing chemical and biological waste to the waste disposal closet (and replacing with new bags/containers), emptying vacuum traps in tissue culture and main lab and refilling with bleach - Debdatta
	+Tissue culture maintenance - replacing water pans in the incubators and treating with Aquaguard (biweekly to monthly), replacing water in the water bath and treating with Aquaguard (monthly), autoclaving incubator racks (bi-annually), disinfection in case of a contamination, keeping the tissue culture room stocked with supplies – Rony
	+Aliquoting of common reagents - aliquoting FBS, pen-strep, glutamine, Aquaguard 1&2 on a regular basis for the whole lab and keeping these reagents in stock – Debdatta
	+Keeping common consumables and reagents in stock - Rotem
3. Lab organization/setup (esp. including when moving to the new building) - Alissa
4. Lab safety - Alissa

Non-experimental:
 (Julie, Avishay, Mike, Michael, Noam H, Noam G)
5. Ordering office supplies - Noam H/Noam G/Michael
6. Milk & machonkolet – Avishay & Noam H/Noam G/Michael
7. Coffee machine supplies and maintenance - Noam H/Noam G/Michael
8. Group meetings  - Julie
9. journal club organization – Mike
10. Lab trip organization: Noam H & Michael 
11. Lab code – Julie & Avishay
12. Lab data – Mike & Noam G




