# Ordering {#ordering}

## Weizmann warehouse orders
An ongoing list for the ordering of lab supplies from the Weizmann warehouse (machsan) is kept on the whiteboard outside Itay’s office. Items ordered from the machsan include all disposables (i.e. tubes, gloves, pipettes), common/basic equipment (i.e timers, pipettors, lab coats), most tissue culture reagents (i.e. media, PBS), basic chemicals (i.e. ethanol, DMSO), and commonly used reagents (i.e. kits for qPCR, cDNA synthesis, RNA isolation). Warehouse orders are placed through the Tafnit system. Alissa regularly places orders but Rotem and Rony also have access to Tafnit (if anyone else would like access, please ask Michal Ovadia; note that the system is only available in Hebrew). When an item on the list is ordered, it should be marked with a checkmark. When the item arrives, it should be erased from the list. Orders from the machsan usually arrive within 3-4 days of being placed. If it is urgent, it is possible to call the warehouse and arrange to pick up an item in person from Piccioto after the order is received.

## General ordering
All items that aren’t ordered from the warehouse can be ordered with a price quote. In principle, some items from Sigma and Grafiti can also be ordered via Tafnit, though it is usually easier to order via price quote. Receiving a price quote requires knowing the local distributor of the product - many company websites will have a list of international distributors. Below, you will also find contact info for many of the most relevant distributors. 

To receive a price quote, email the relevant distributor with the catalog number and manufacturer. You can also ask how long it will take for the product to arrive if it’s time sensitive (many products are ordered from abroad). Include in the quote request or in your email signature that you are from the Tirosh lab and lab address/departmental affiliation. You can forward price quotes to Natali (natalie.yikne@weizmann.ac.il) and she will place the order. 
 
## Office supplies
 Graffiti is the office supply distributor for the Weizmann Institute. Their inventory/catalog can be found on [their website](https://www.graffiti-online.co.il/). You can receive a price quote from liatji@graf.co.il. 

## Antibodies
 In the Tirosh Lab dropbox, there is an [excel file](https://www.dropbox.com/s/8fr2p795g5zgepz/antibodies_Tirosh.xlsx?dl=0) listing the details of the antibodies we have in the lab. Please consult it before ordering a new antibody and please update it when you receive a new antibody. Biocompare.com is a useful site for finding antibodies. You can filter your search with reactive species, conjugated fluorophores, and by application (IHC, flow, etc). There are many vendors of varying reputation for antibodies  — please ask if you have questions about quality or which vendor to choose. For selecting fluorophores for FACS antibodies, the [BD spectrum viewer](https://www.bdbiosciences.com/en-us/applications/research-applications/multicolor-flow-cytometry/product-selection-tools/spectrum-viewer) is a helpful tool for selecting panels of antibodies without spectral overlap.


Below are some recommended antibody vendors and their local distributors.

For FACS antibodies:

- eBioscience (Rhenium), Biolegend (Enco), Miltenyi (Almog)

For immunohistochemistry/immunocytochemistry antibodies:

- Abcam (Zotal), R&D (Biotest)

For price quotes:

- Rhenium (eBioscience, Thermofisher) - Yaara Willensky yaara@rhenium.co.il
- Almog (Miltenyi) - Aviva Blechman Peretz aviva@almog.co.il
- Biotest (R&D) - Laora laora@biotest.co.il
- Zotal (Abcam) -  Anna Bernstein anna@zotal.co.il
- Enco (Biolegend) - Yifat Ovadia - Yifat@enco.co.il

## Molecular biology
Many popular molecular biology kits/products can be found in the warehouse (for qPCR we are typically using Applied Biosystems FAST SYBR green, for cDNA synthesis we like the Applied Biosystems high capacity cDNA kit, both available from the warehouse). For RNA isolation, Qiagen kits are available from the warehouse, though our favorite is the Zymo Quick RNA micro prep kit (Zotal is the distributor). 

## Growth factors
Please check the [growth factors/cytokine spreadsheet](https://www.dropbox.com/s/q0dn3a3th12y822/cytokines_GFs_Tirosh.xlsx?dl=0) in the Tirosh Lab dropbox to see inventory and please update when you receive something new. We have good experience ordering growth factors/cytokines from Peprotech located in Park HaMada (email ori@peprotechasia.com for quotes) and from Sino Biological (email Yifat Ovadia  - Yifat@enco.co.il for a quote). 

## Miltenyi/MACS products
Almog is the supplier for Miltenyi products including reagents/disposables for the OctoMACS tissue dissociator, the dead cell removal kit, and MACS beads/reagants. Email aviva@almog.co.il or netta@almog.co.il for quotes. There is an option to either place an individual order or to join the monthly departmental order which saves money but takes longer. If your order is non-urgent, you can request the FOB price and ask Natali to add it to the monthly departmental order when you send her the quote.

## Drugs
Cayman Chemicals is a reasonably priced and reliable supplier for drugs/compounds. Their distributor is Enco (Yifat@enco.co.il for quotes). Other vendors for drugs/chemical compounds include Sigma/Merck (shir.yohai@merckgroup.com), Molport (jose.garcia-tenorio@molport.com), and Selleck (manager@tivanbiotech.com).

## Chemicals
Sigma/Merck is the largest distributor for chemicals. Many common chemicals can be ordered via the warehouse; Sigma price quote requests can be sent to shir.yohai@merckgroup.com.

## Primers
For primer design, everyone has their favorite program, but NCBI Primer BLAST is a good place to start. We order primers through IDT/Syntezza (idtdna.com). You can create your own user account with IDT on their site. Since primers are inexpensive and we tend to place small orders, we keep a standing order with IDT. In the payment order field, you can write ‘Tirosh lab standing order’. You can email Chany Frankel (chany@syntezza.com) to confirm that there is money remaining in the standing order or to request to add money to the standing order via a price quote.

## Illumina kits
Danyel Biotech is the distributor for Illumina sequencing kits (request a quote from sigal@danyel.co.il). The current kit in use for the NextSeq 500/550 is the NextSeq 500 high output kit (75 cycles) FC-4-4-2005. 

