# Lab GitHub Account {#labGitHub}

The lab has a shared github account called `tiroshlab` [(GitHub Repo)](https://github.com/tiroshlab). This allows an unlimited number of us to collaborate on multiple projects (also known as *repositories*) at once, and also provides a page to which non-lab-members can navigate to see, download or contribute (upon request) to our code.


## How do I join?
To become a member of the account, you should send your GitHub username to Julie (julie.laffy@weizmann.ac.il) or to Mike (michael.tyler@weizmann.ac.il). If you don't have a personal account, you should first sign up at [this link](https://github.com/signup). Once you're added, you'll be able to easily make changes to existing projects or add new ones.


## What is an organization account and how do I sign in?
`tiroshlab` is an organization account: like personal accounts, organizations can own resources such as repositories, packages, and projects. However, **you cannot sign into an organization.** Instead, **each person signs into their own personal account, and any actions the person takes on organization resources are attributed to their personal account.** Each personal account can be a member of multiple organizations.

### Additional links
- [Types of GitHub accounts](https://docs.github.com/en/get-started/learning-about-github/types-of-github-accounts)
- [Committing code to an organization repo](https://stackoverflow.com/questions/35745358/can-a-github-organization-commit-code-to-a-repository)
- [Committing on behalf of an organization](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-on-behalf-of-an-organization)


## How do I add or edit a repository?
### Option 1: Using the GitHub website
- To add a new repository, navigate to the `tiroshlab` [GitHub Repo](https://github.com/tiroshlab), and click the green **New** button.
- To make changes to an existing repository, navigate to the GitHub page in question (e.g. [3CA project](https://github.com/tiroshlab/3ca)) and use the icons to add files or open existing files.

### Option 2: Using the git command line interface
Proceed as you would for any other git repository, using your personal git credentials to push/pull commits to the `tiroshlab` repository.


## The lab book repository
The lab book is one of the GitHub repositories on the `tiroshlab` account [(GitHub Repo)](https://github.com/tiroshlab/lab-book). Therefore, you can add or edit it as you would any other repository. However, we also build the lab book as a website using GitHub pages [(Website)](https://tiroshlab.github.io/lab-book/). The Github Repo and the Website are synced, so it doesn't matter which 'form' of the lab book you make your edits to. 

See [Section 1.2: Adding to the book](https://tiroshlab.github.io/lab-book/index.html#adding-to-the-book) for step-by-step instructions on adding to the book.

