--- 
title: "Tirosh Lab Book"
date: "Last updated on `r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: tiroshlab/lab-book
description: "Help & guidelines for members of the Tirosh lab"
---

# Homepage 

## Links

### Useful
- [Lab Dropbox](https://www.dropbox.com/home/Tirosh%20Lab)  
- [Lab GitHub (tiroshlab)](https://www.github.com/tiroshlab)  
- [Lab Publications](http://www.weizmann.ac.il/mcb/tirosh/publications-0)  
- [Lab Website](http://www.weizmann.ac.il/mcb/tirosh/)  
- [Lab Experimental Protocols](https://www.dropbox.com/sh/javjoi26i5k5f6t/AADAX4RgSZUFuBwtS6TRE3wua?dl=0)  

### Fun
- [Lab Twitter](https://twitter.com/tiroshlab)  
- [Birthdays](https://www.dropbox.com/s/zwss5fg9rkoz7pp/lab%20bday%20list.xlsx?dl=0)  
- [Lab Members](http://www.weizmann.ac.il/mcb/tirosh/group-members)  
- [Lab Pictures :)](http://www.weizmann.ac.il/mcb/tirosh/pictures)  

## Adding to the book
Adding to the lab book is easy. The only requirement is that you [make a Github account](https://github.com/join?source=header-home), which shouldn't take more than a couple of minutes to do.

Note that since the book is re-built with each edit made, **you may have to wait a few minutes before your changes become visible**.

### Option 1
1. Go to the website chapter that you would like to edit.
    + E.g. [Chapter 3 Lab members and contact details](https://tiroshlab.github.io/lab-book/contact.html)
2. Click on the edit icon at the top of the website page.
3. Make your edits and submit them (green button at the bottom of the page).

### Option 2
**Note**: this will only work for those whose Github users have been added to the book repository.

1. Go to your local clone of the repository.
    + to clone the repository: `git clone https://github.com/tiroshlab/lab-book.git`  
2. Make and save the relevant changes to the .Rmd file in question.
    + There is one .Rmd file per chapter.
3. Submit the edit. In the terminal type:
    + `git commit -am <myShortMessage>`
    + `git pull origin master`
    + `git push origin master`

### Writing in rmarkdown
The book is written in rmarkdown (file extension Rmd). There is one Rmd file per chapter, so when you click the edit icon you are opening the file chapterX.Rmd. Writing in a Rmd file is similar to writing in a normal text document but with some required syntax to bear in mind, namely for:
    + New lines
    + New paragraphs
    + Sections, subsections, subsubsections etc
    + List items (bulleted or numbered)

[This 1-page cheatsheet](https://rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf) covers all of the basics and [this book on (publishing with) rmarkdown](https://bookdown.org/yihui/rmarkdown) is a useful guide for those interested in finding out more.

## Book formats
The default book is a [website](https://tiroshlab.github.io/lab-book). You can also choose to download the book as PDF or ebook. To do this, click the download icon at the top of the website page. 

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
